### ISSUE TITLE
No Standard Plan available for Speech to Text anymore

### ISSUE THREAD

**Issue by kwiatks** [IBM/build-custom-stt-model-with-diarization#4]
https://github.com/IBM/build-custom-stt-model-with-diarization/blob/master/README.md#2-create-watson-speech-to-text-service

Standard Plan not available anymore 

➜  build-custom-stt-model-with-diarization git:(master) ✗ **docker run -p 8080:8080 stt-with-diarization**
Traceback (most recent call last):
  File "app.py", line 64, in <module>
    language_models = speech_to_text.list_language_models().get_result()
  File "/usr/local/lib/python3.8/dist-packages/ibm_watson/speech_to_text_v1.py", line 1443, in list_language_models
    response = self.send(request)
  File "/usr/local/lib/python3.8/dist-packages/ibm_cloud_sdk_core/base_service.py", line 308, in send
    raise ApiException(response.status_code, http_response=response)
ibm_cloud_sdk_core.api_exception.ApiException: **Error: This feature is not available for the Bluemix Lite plan. Please upgrade to a paid plan to activate this feature: https://console.bluemix.net/catalog/services/speech-to-text, Code: 400 , X-global-transaction-id: e201f0ca-b2c2-4ab2-84be-681fb13d0208**

**Comment by kwiatks** [comment]
Upgraded from Lite to "Plus - NEW!" - still get same error as above

**Comment by kwiatks** [comment]
After upgrading you need to get new credentials - then rebuilt docker image and then didn't get the above issue anymore
